# Generated by Django 4.2.13 on 2024-06-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImagingCenter",
            fields=[
                ("center_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("location", models.TextField(default="No location provided")),
                ("phone", models.TextField(default="No services listed")),
                (
                    "operational_hours",
                    models.TextField(default="No operational hours provided"),
                ),
            ],
        ),
    ]
