# Generated by Django 4.2.13 on 2024-06-28 05:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_merge_20240627_1445"),
        ("imaging_center", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImagingAppointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appointment_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "appointment_time",
                    models.TimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "imaging_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="imaging_center.imagingcenter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.patientprofile",
                    ),
                ),
            ],
        ),
    ]
