# Generated by Django 4.2.13 on 2024-06-27 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_is_technician_technicianprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="RadiologyImage",
            fields=[
                ("image_id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="radiology_images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="radiology_images",
                        to="users.patientprofile",
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        limit_choices_to={"is_technician": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
