# Generated by Django 4.2.13 on 2024-06-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_radiologyimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="radiologyimage",
            name="user_id",
            field=models.CharField(default="00000", max_length=30),
        ),
    ]
