# Generated by Django 4.2.13 on 2024-06-27 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_radiologyimage_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="radiologyimage",
            name="technician",
            field=models.ForeignKey(
                limit_choices_to={"is_technician": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="users.technicianprofile",
            ),
        ),
    ]
