# Generated by Django 4.2.13 on 2024-06-27 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_radiologyimage_technician"),
    ]

    operations = [
        migrations.RemoveField(model_name="radiologyimage", name="technician",),
    ]
