# Generated by Django 4.2.13 on 2024-06-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_dentistprofile_speciality'),
        ('users', '0008_remove_radiologyimage_technician'),
    ]

    operations = [
    ]
