# Generated by Django 4.2.13 on 2024-06-27 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("donor_name", models.CharField(max_length=100)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("email", models.EmailField(max_length=254)),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "message",
                    models.TextField(
                        blank=True, default="Thank you for your donation!", null=True
                    ),
                ),
            ],
        ),
    ]
